#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    Nop = 0,
    LoadConst = 1,
    LoadLocal = 2,
    StoreLocal = 3,
    Move = 4,
    AddInt = 5,
    AddFloat = 6,
    AddSizeChecked = 7,
    AddByteWrap = 8,
    SeqBuild = 9,
    SeqPush = 10,
    SeqGetChecked = 11,
    SeqGetUnchecked = 12,
    SeqSetChecked = 13,
    SeqSetUnchecked = 14,
    FieldGet = 15,
    FieldSet = 16,
    StructConstruct = 17,
    VariantConstruct = 18,
    CallDirect = 19,
    CallBound = 20,
    CallWitness = 21,
    CallHost = 22,
    Jump = 23,
    JumpIfFalse = 24,
    MatchVariant = 25,
    FiniteForInit = 26,
    FiniteForNext = 27,
    ResultPropagate = 28,
    SpawnTask = 29,
    TaskJoin = 30,
    StringBuild = 31,
    Panic = 32,
    Return = 33,
    GreaterInt = 34,
    VariantField = 35,
    EqualInt = 36,
    NotEqualInt = 37,
    LessInt = 38,
    LessEqualInt = 39,
    GreaterEqualInt = 40,
}

impl Opcode {
    pub const ALL: &'static [Self] = &[
        Self::Nop,
        Self::LoadConst,
        Self::LoadLocal,
        Self::StoreLocal,
        Self::Move,
        Self::AddInt,
        Self::AddFloat,
        Self::AddSizeChecked,
        Self::AddByteWrap,
        Self::SeqBuild,
        Self::SeqPush,
        Self::SeqGetChecked,
        Self::SeqGetUnchecked,
        Self::SeqSetChecked,
        Self::SeqSetUnchecked,
        Self::FieldGet,
        Self::FieldSet,
        Self::StructConstruct,
        Self::VariantConstruct,
        Self::CallDirect,
        Self::CallBound,
        Self::CallWitness,
        Self::CallHost,
        Self::Jump,
        Self::JumpIfFalse,
        Self::MatchVariant,
        Self::FiniteForInit,
        Self::FiniteForNext,
        Self::ResultPropagate,
        Self::SpawnTask,
        Self::TaskJoin,
        Self::StringBuild,
        Self::Panic,
        Self::Return,
        Self::GreaterInt,
        Self::VariantField,
        Self::EqualInt,
        Self::NotEqualInt,
        Self::LessInt,
        Self::LessEqualInt,
        Self::GreaterEqualInt,
    ];
}
