#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    Nop = 0,
    LoadConst = 1,
    LoadLocal = 2,
    StoreLocal = 3,
    Move = 4,
    AddInt = 5,
    AddFloat = 6,
    AddSizeChecked = 7,
    AddByteWrap = 8,
    SeqBuild = 9,
    SeqPush = 10,
    SeqGetChecked = 11,
    SeqGetUnchecked = 12,
    SeqSetChecked = 13,
    SeqSetUnchecked = 14,
    FieldGet = 15,
    FieldSet = 16,
    StructConstruct = 17,
    VariantConstruct = 18,
    CallDirect = 19,
    CallBound = 20,
    CallWitness = 21,
    CallHost = 22,
    Jump = 23,
    JumpIfFalse = 24,
    MatchVariant = 25,
    FiniteForInit = 26,
    FiniteForNext = 27,
    ResultPropagate = 28,
    SpawnTask = 29,
    TaskJoin = 30,
    StringBuild = 31,
    Panic = 32,
    Return = 33,
    GreaterInt = 34,
    VariantField = 35,
    EqualInt = 36,
    NotEqualInt = 37,
    LessInt = 38,
    LessEqualInt = 39,
    GreaterEqualInt = 40,
    NegInt = 41,
    NotBool = 42,
    RangeExclusiveInt = 43,
    RangeInclusiveInt = 44,
    CallableValue = 45,
    StructIs = 46,
    TupleBuild = 47,
    SubInt = 48,
    MulInt = 49,
    DivInt = 50,
    RemInt = 51,
    BitNotInt = 52,
    BitAndInt = 53,
    BitOrInt = 54,
    BitXorInt = 55,
    ShiftLeftInt = 56,
    ShiftRightInt = 57,
    NoneCheck = 58,
    SubFloat = 59,
    MulFloat = 60,
    DivFloat = 61,
    GreaterFloat = 62,
    EqualFloat = 63,
    NotEqualFloat = 64,
    LessFloat = 65,
    LessEqualFloat = 66,
    GreaterEqualFloat = 67,
    SubSizeChecked = 68,
    MulSizeChecked = 69,
    DivSize = 70,
    RemSize = 71,
    GreaterSize = 72,
    EqualSize = 73,
    NotEqualSize = 74,
    LessSize = 75,
    LessEqualSize = 76,
    GreaterEqualSize = 77,
    SubByteWrap = 78,
    MulByteWrap = 79,
    DivByte = 80,
    RemByte = 81,
    BitNotByte = 82,
    BitAndByte = 83,
    BitOrByte = 84,
    BitXorByte = 85,
    ShiftLeftByte = 86,
    ShiftRightByte = 87,
    GreaterByte = 88,
    EqualByte = 89,
    NotEqualByte = 90,
    LessByte = 91,
    LessEqualByte = 92,
    GreaterEqualByte = 93,
}

impl Opcode {
    pub const ALL: &'static [Self] = &[
        Self::Nop,
        Self::LoadConst,
        Self::LoadLocal,
        Self::StoreLocal,
        Self::Move,
        Self::AddInt,
        Self::AddFloat,
        Self::AddSizeChecked,
        Self::AddByteWrap,
        Self::SeqBuild,
        Self::SeqPush,
        Self::SeqGetChecked,
        Self::SeqGetUnchecked,
        Self::SeqSetChecked,
        Self::SeqSetUnchecked,
        Self::FieldGet,
        Self::FieldSet,
        Self::StructConstruct,
        Self::VariantConstruct,
        Self::CallDirect,
        Self::CallBound,
        Self::CallWitness,
        Self::CallHost,
        Self::Jump,
        Self::JumpIfFalse,
        Self::MatchVariant,
        Self::FiniteForInit,
        Self::FiniteForNext,
        Self::ResultPropagate,
        Self::SpawnTask,
        Self::TaskJoin,
        Self::StringBuild,
        Self::Panic,
        Self::Return,
        Self::GreaterInt,
        Self::VariantField,
        Self::EqualInt,
        Self::NotEqualInt,
        Self::LessInt,
        Self::LessEqualInt,
        Self::GreaterEqualInt,
        Self::NegInt,
        Self::NotBool,
        Self::RangeExclusiveInt,
        Self::RangeInclusiveInt,
        Self::CallableValue,
        Self::StructIs,
        Self::TupleBuild,
        Self::SubInt,
        Self::MulInt,
        Self::DivInt,
        Self::RemInt,
        Self::BitNotInt,
        Self::BitAndInt,
        Self::BitOrInt,
        Self::BitXorInt,
        Self::ShiftLeftInt,
        Self::ShiftRightInt,
        Self::NoneCheck,
        Self::SubFloat,
        Self::MulFloat,
        Self::DivFloat,
        Self::GreaterFloat,
        Self::EqualFloat,
        Self::NotEqualFloat,
        Self::LessFloat,
        Self::LessEqualFloat,
        Self::GreaterEqualFloat,
        Self::SubSizeChecked,
        Self::MulSizeChecked,
        Self::DivSize,
        Self::RemSize,
        Self::GreaterSize,
        Self::EqualSize,
        Self::NotEqualSize,
        Self::LessSize,
        Self::LessEqualSize,
        Self::GreaterEqualSize,
        Self::SubByteWrap,
        Self::MulByteWrap,
        Self::DivByte,
        Self::RemByte,
        Self::BitNotByte,
        Self::BitAndByte,
        Self::BitOrByte,
        Self::BitXorByte,
        Self::ShiftLeftByte,
        Self::ShiftRightByte,
        Self::GreaterByte,
        Self::EqualByte,
        Self::NotEqualByte,
        Self::LessByte,
        Self::LessEqualByte,
        Self::GreaterEqualByte,
    ];
}
