#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    Nop = 0,
    LoadConst = 1,
    LoadLocal = 2,
    StoreLocal = 3,
    Move = 4,
    AddInt = 5,
    AddFloat = 6,
    AddSizeChecked = 7,
    AddByteWrap = 8,
    SeqBuild = 9,
    SeqPush = 10,
    SeqGetChecked = 11,
    SeqGetUnchecked = 12,
    SeqSetChecked = 13,
    SeqSetUnchecked = 14,
    FieldGet = 15,
    FieldSet = 16,
    VariantConstruct = 17,
    CallDirect = 18,
    CallBound = 19,
    CallWitness = 20,
    CallHost = 21,
    Jump = 22,
    JumpIfFalse = 23,
    MatchVariant = 24,
    FiniteForInit = 25,
    FiniteForNext = 26,
    ResultPropagate = 27,
    SpawnTask = 28,
    TaskJoin = 29,
    StringBuild = 30,
    Panic = 31,
    Return = 32,
}

impl Opcode {
    pub const ALL: &'static [Self] = &[
        Self::Nop,
        Self::LoadConst,
        Self::LoadLocal,
        Self::StoreLocal,
        Self::Move,
        Self::AddInt,
        Self::AddFloat,
        Self::AddSizeChecked,
        Self::AddByteWrap,
        Self::SeqBuild,
        Self::SeqPush,
        Self::SeqGetChecked,
        Self::SeqGetUnchecked,
        Self::SeqSetChecked,
        Self::SeqSetUnchecked,
        Self::FieldGet,
        Self::FieldSet,
        Self::VariantConstruct,
        Self::CallDirect,
        Self::CallBound,
        Self::CallWitness,
        Self::CallHost,
        Self::Jump,
        Self::JumpIfFalse,
        Self::MatchVariant,
        Self::FiniteForInit,
        Self::FiniteForNext,
        Self::ResultPropagate,
        Self::SpawnTask,
        Self::TaskJoin,
        Self::StringBuild,
        Self::Panic,
        Self::Return,
    ];
}
