use tune_diagnostics::Span;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenKind {
    Whitespace,
    LineComment,
    BlockComment,
    Ident,
    IntLiteral,
    FloatLiteral,
    StringLiteral,
    MultilineStringLiteral,
    KeywordLet,
    KeywordStruct,
    KeywordEnum,
    KeywordTag,
    KeywordIf,
    KeywordElif,
    KeywordElse,
    KeywordMatch,
    KeywordFor,
    KeywordIn,
    KeywordWhile,
    KeywordLoop,
    KeywordBreak,
    KeywordContinue,
    KeywordReturn,
    KeywordSpawn,
    KeywordImport,
    KeywordPub,
    KeywordPanic,
    KeywordNever,
    KeywordOk,
    KeywordError,
    KeywordTrue,
    KeywordFalse,
    KeywordNone,
    KeywordSelf,
    KeywordNot,
    KeywordAnd,
    KeywordOr,
    KeywordIs,
    At,
    Bang,
    Question,
    Tilde,
    Amp,
    Pipe,
    Caret,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Equal,
    EqualEqual,
    TildeEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    ShiftLeft,
    ShiftRight,
    Arrow,
    FatArrow,
    Colon,
    ColonColon,
    Dot,
    DotDot,
    Comma,
    Semicolon,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Eof,
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    #[must_use]
    pub const fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}
