#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenKind {
    Ident,
    IntLiteral,
    FloatLiteral,
    StringLiteral,
    MultilineStringLiteral,
    KeywordLet,
    KeywordStruct,
    KeywordEnum,
    KeywordTag,
    KeywordIf,
    KeywordElif,
    KeywordElse,
    KeywordMatch,
    KeywordFor,
    KeywordIn,
    KeywordWhile,
    KeywordLoop,
    KeywordBreak,
    KeywordContinue,
    KeywordReturn,
    KeywordSpawn,
    KeywordImport,
    KeywordPub,
    KeywordTrue,
    KeywordFalse,
    KeywordNone,
    KeywordSelf,
    KeywordNot,
    KeywordAnd,
    KeywordOr,
    KeywordIs,
    Symbol,
    Eof,
    Error,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub text: String,
    pub start: u32,
    pub end: u32,
}
